### ISSUE TITLE
VR view feature

### ISSUE THREAD

**Issue by jakerator** [smerf-3d/smerf-3d.github.io#4]
I see you're using three.js for rendering. So is it possible to enable VR mode using built-in [three.js code](https://threejs.org/docs/#manual/en/introduction/How-to-create-VR-content)  ?
Really interesting how this amazing blow-mind scene looks in VR

**Comment by duckworthd** [comment]
This is unfortunately not a feature we are looking into (we're researchers!). Being said, if you have the skills to make it happen, go for it!
