### ISSUE TITLE
Training code?

### ISSUE THREAD

**Issue by antithing** [smerf-3d/smerf-3d.github.io#7]
Hi! Will this code ever be released?

Thanks!

**Comment by Liuksataka** [comment]
Yeah. I got dissapointed quick...

**Comment by Ezharjan** [comment]
+1

**Comment by samhodge-aiml** [comment]
it is released

**Comment by Ezharjan** [comment]
> it is released

Thanks!

**Comment by duckworthd** [comment]
Training code is available here: https://github.com/google-research/google-research/tree/master/smerf
