### ISSUE TITLE
can you use camp_zipnerf with webbased smerf viewer?

### ISSUE THREAD

**Issue by comsyspro** [smerf-3d/smerf-3d.github.io#8]
is it possible to create a webbased walkthrough in combination with camp_zipnerf and smerf-3d?

camp_zipnerf github project:
https://github.com/jonbarron/camp_zipnerf

if yes, how to use the content and include it into the smerf viewer? are there any tutorials?

**Comment by duckworthd** [comment]
Check out https://github.com/google-research/google-research/tree/master/smerf for instructions on turning `camp_zipnerf` models into SMERF models.
